# syntax=docker/dockerfile:1

# Assumes that dist/*.whl has been built

FROM thehale/python-poetry:2.1.3-py3.11-slim AS python-base

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    cargo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./dist/*.whl ./

RUN pip install *.whl

CMD ["ouroboros-docker-server"]