# syntax=docker/dockerfile:1

# Assumes that dist/*.whl has been built

FROM thehale/python-poetry:2.1.3-py3.11-slim@sha256:4e091da0d71700b404a2844ac3bbd4aaa3450a6421c469935ae165d41252a964 AS python-base

ENV DCONF_DISABLE_ASYNC=1

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    cargo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./dist/*.whl ./

RUN pip install *.whl

CMD ["ouroboros-docker-server"]
