[tool.poetry]
name = "ouroboros"
version = "1.1.0"
description = "Extract ROIs (e.g. nerves, blood vessels) from multi-terabyte cloud-hosted medical scans."
authors = ["Weaver Goldman <we.goldm@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
ouroboros-cli = "ouroboros.cli:main"
ouroboros-server = "ouroboros.server:main"
ouroboros-docker-server = "ouroboros.docker_server:main"
build-cli-executable = "pyinstaller:build_cli_executable"
build-server-executable = "pyinstaller:build_server_executable"

# Use python 3.10
# https://stackoverflow.com/questions/60580113/change-python-version-to-3-x and run poetry install, poetry lock
[tool.poetry.dependencies]
python = ">=3.11,<3.13"
numpy = "^1.26.4"
scipy = "^1.13.1"
cloud-volume = { url = "https://github.com/den-sq/cloud-volume/releases/download/12.2.0a0/cloud_volume-12.2.0a0-py3-none-any.whl" }
compresso = "^3.0.0"
tifffile = "^2024.6.18"
pydantic = "^2.7.4"
tqdm = "^4.66.4"
imagecodecs = "^2024.6.1"
fastapi = "^0.115.0"
asyncio = "^3.4.3"
uuid = "^1.30"
sse-starlette = "^2.3.2"
typing-extensions = "^4.14.0"
uvicorn = "^0.29.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pytest-cov = "^6.1.1"
pyinstaller = "^6.13.0"
setuptools = "^78.1.1"
coverage = "^7.6.0"
autopep8 = "^2.3.2"
viztracer = "^1.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
