name: Build and Release App

on:
  push:
    tags:
      - v*.*.*

env: 
  GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.8.3'

      - name: Install Dependencies
        working-directory: ./python
        run: poetry install

      - name: Build Wheel
        working-directory: ./python
        run: poetry build

      - name: Copy Python Server Executable Mac or Linux
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          mkdir -p ./extra-resources/server/dist/
          cp -r ./python/dist/* ./extra-resources/server/dist/
          cp ./python/Dockerfile-prod ./extra-resources/server/Dockerfile
          cp ./python/compose.yml ./extra-resources/server/compose.yml

      - name: Copy Python Server Executable Windows
        if: matrix.os == 'windows-latest'
        run: |
          New-Item -Path ./extra-resources/server/dist/ -ItemType Directory -Force
          Copy-Item -Path ./python/dist/* -Destination ./extra-resources/server/dist/ -Recurse
          Copy-Item -Path ./python/Dockerfile-prod -Destination ./extra-resources/server/Dockerfile
          Copy-Item -Path ./python/compose.yml -Destination ./extra-resources/server/compose.yml
        shell: powershell

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap