name: Build and Release App

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
        
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install Dependencies
        working-directory: ./python
        run: poetry install

      - name: Build Python Server with PyInstaller
        working-directory: ./python
        run: poetry run build-server-executable

      - name: Copy Python Server Executable Linux
        if: matrix.os == 'ubuntu-latest'
        run: cp -r ./python/dist/* ./resources/

      - name: Copy Python Server Executable Mac
        if: matrix.os == 'macos-latest'
        run: cp -r ./python/dist/* ./resources/

      - name: Copy Python Server Executable Windows
        if: matrix.os == 'windows-latest'
        run: Copy-Item -Path ./python/dist/* -Destination ./resources/ -Recurse
        shell: powershell

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}