name: PR Test Coverage
on:
  pull_request:
    branches:
      - main

env: 
  GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.8.3'

      - name: Install Dependencies
        working-directory: ./python
        run: poetry install

      - name: Run Tests
        run: |
          poetry run coverage run --source=ouroboros/helpers -m pytest 
          poetry run coverage report -m
          poetry run coverage xml
        working-directory: ./python

# orgoro does not work in workflow runs due to fork permissions issues:
# See PR https://github.com/orgoro/coverage/pull/281
# So commenting it out for now.
# 
#      - name: Get Cover 
#         uses: orgoro/coverage@v3.2
#         with:
#           coverageFile: python/coverage.xml
#           token: ${{ secrets.GITHUB_TOKEN }}