name: PR Test Coverage
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: "3.10"
          poetry-version: "1.8.3"

      - name: Run Tests
        run: |
          poetry run coverage run --source=ouroboros/helpers -m pytest 
          poetry run coverage report -m
          poetry run coverage xml
        working-directory: ./python

      - name: Get Cover 
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: python/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}